[package]
name = "kmer_index"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
bio = "3.0.0"
clap = { version = "4.5.53",features = ["derive"] }
rand = "0.9.2"
rustc-hash = "2.1.1"
smallvec = "1.15.1"

